tinyMCE.addI18n('en.biblepost',{
	descripcion:"Put a Bible quote",
	titulo:"BiblePost WP",
	txt_version:"Version",
	txt_versiculo:"Bible passage",
	txt_clase: "Class",
	txt_mostrarversion:"Show Version",
	txt_n_a:"n/a",
	txt_negacion:"No",
	txt_afirmacion:"Yes",
	txt_necesario:"Fields marked with * are required.",
txt_importar:"Modo de Insercion",
txt_importar_local: "Importado",
txt_importar_remoto: "Vinculado",
txt_importar_advertencia_import:"<b>Importado:</b> Incluira el contenido al post/Base de Datos.",
txt_importar_advertencia_linked:"<b>Vinculado:</b> Cargara el contenido de manera Externa; Se incluye ShortCode a la base de datos.",
txt_hide_s: "Expandido",
txt_hide_h: "Contraido",
txt_contenedor: "Use Container",
        txt_referencias: "Use References"
});